<?php

namespace App\Service\Synchronizer\BackToFront;

use App\Contract\BackToFront\ProductDiscountSpeedSynchronizerContract;
use App\Service\Synchronizer\BackToFront\Implementation\ProductDiscountSpeedSynchronizer as ProductDiscountSpeedSynchronizerBase;

class ProductDiscountSpeedSynchronizer extends ProductDiscountSpeedSynchronizerBase implements ProductDiscountSpeedSynchronizerContract
{
}