synchronize_products_by_ids:
    path:       /products/update/by-ids
    controller: App\Controller\API\ProductController::updateProductsByIdsAction
    methods:    POST

synchronize_products_by_categories_ids:
    path:       /products/update/by-categories-ids
    controller: App\Controller\API\ProductController::updateProductsByCategoriesIdsAction
    methods:    POST

get_categories_tree:
    path:       /category/tree
    controller: App\Controller\API\ProductController::getCategoriesAction
    methods:    GET

get_products:
    path:       /product/search
    controller: App\Controller\API\ProductController::getProductsByNameAction
    methods:    POST

get_order_information:
    path:       /order/back/information/{id}
    controller: App\Controller\API\OrderBackController::orderInformationAction
    methods:    GET
    requirements:
        id: '\d+'

