category:
    path:       /category/tree
    controller: App\Controller\API\ProductController::getCategoriesAction
    methods:    GET

products_by_ids:
    path:       /products/update/by-ids
    controller: App\Controller\API\ProductController::updateProductsByIdsAction
    methods:    POST

products_by_categories_ids:
    path:       /products/update/by-categories-ids
    controller: App\Controller\API\ProductController::updateProductsByCategoriesIdsAction
    methods:    POST